services:
  db:
    image: mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret

  web:
    build: .  # Construir la imagen usando el Dockerfile en el directorio actual
    depends_on:
      - db
    volumes:
      - ./target:/var/www/html
      - ./wp-includes/js:/var/www/html/wp-includes/js
    environment:
      - WORDPRESS_DB_USER=manager
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - 5000:80

volumes:
  data:
